spring:
  application:
    name: ai-chat
  data:
    redis:
      database: 1
      host: 192.168.31.105
    mongodb:
      uri: mongodb://192.168.31.105:27017/chatDB

langchain4j:
  models:
    gemini:
      api-model:
        api-key: AIzaSyDf8AumGRKxpZwWGVTYsr3hlxeXZPQ9quQ
        model-name: gemini-2.0-flash
        temperature: 0.7