FROM ubuntu:latest
LABEL authors="Shuan"
 wget https://github.com/milvus-io/milvus/releases/download/v2.6.0-rc1/milvus-standalone-docker-compose.yml -O docker-compose-milvus.yml
ENTRYPOINT ["top", "-b"]