server:
  port: 8080

spring:
  application:
    name: bot
  main:
    allow-circular-references: true
  data:
    #    redis:
    #      database: 1
    #      host:
    #    mongodb:
    #      uri: mongodb://:27017/chatDB
    redis:
      database: 1
      host: 172.18.32.160
    mongodb:
      host: 8.138.204.38
      port: 27017
      database: chatDB
    milvus:
      url: ${milvus.url}
      host: ${milvus.host}
      port: ${milvus.port}
      defaultDatabaseName: ${milvus.defaultDatabaseName}
      defaultCollectionName: ${milvus.defaultCollectionName}
  servlet:
    multipart:
      max-file-size: 20MB
langchain4j:
  models:
    gemini:
      apiKey: AIzaSyDf8AumGRKxpZwWGVTYsr3hlxeXZPQ9quQ
      modelName: gemini-2.0-flash
      temperature: 0.7
    qwen:
      apiKey: sk-ef837a5f684c4ed087802c948857df5f
      location: us-central1
      modelName: text-embedding-v2
    ollama:
      url: http://8.138.204.38:11434
      modelName: gemma3:12b
      temperature: 0.8

milvus:
  url: http://172.18.32.160:19530
  host: 172.18.32.160
  port: 19530
  defaultDatabaseName: chatEmbeddingDB6
  defaultCollectionName: rag_embedding_collection
  topK: 5