server:
  port: 8080

spring:
  application:
    name: bot
  main:
    allow-circular-references: true
  data:
    redis:
      database: 1
      host: 8.138.204.38
    mongodb:
      host: 8.138.204.38
      port: 27017
      database: storeDB
      username: root
      password: example
      authentication-database: admin
    milvus:
      url: ${milvus.url}
      host: ${milvus.host}
      port: ${milvus.port}
      defaultDatabaseName: ${milvus.defaultDatabaseName}
      defaultCollectionName: ${milvus.defaultCollectionName}
  servlet:
    multipart:
      max-file-size: 20MB
  neo4j:
    uri: bolt://8.138.204.38:7687
#    uri: bolt://8.138.204.38:7687
    authentication:
      username: neo4j
      password: password
langchain4j:
  models:
    gemini:
      apiKey: AIzaSyDf8AumGRKxpZwWGVTYsr3hlxeXZPQ9quQ
      modelName: gemini-2.0-flash
      temperature: 0.7
    qwen:
      apiKey: sk-ef837a5f684c4ed087802c948857df5f
      location: us-central1
      modelName: text-embedding-v2
    ollama:
      url: http://localhost:11434
      modelName: gemma3:12b
      temperature: 0.8

milvus:
  uri: http://8.138.204.38:19530
  enable: true
  open-log: true
  db-name: ${milvus.defaultDatabaseName}
  packages:
    - com.shuanglin.dao.milvus
  top-k: 5
  defaultDatabaseName: milvusDB
  defaultCollectionName: novelCollection